name: Actualizar Precios Carne VZLA

on:
  workflow_dispatch: # Para que puedas darle al botón gris manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Ejecutar script de precios
        run: python actualizar_precios.py

      - name: Guardar cambios y publicar
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add precios.json
          git commit -m "Precios reales actualizados" || exit 0
          git push
